### ISSUE TITLE
Copiar DLServiceWrapperHook para control de attachments en wiki y web content

### ISSUE THREAD

**Issue by juanferrub** [LSUG-Projects/quota-control-portlet#16]

**Comment by juangon** [comment]
Hola @juanferrub, me pregunto qué quiere decir esto....

**Comment by juanferrub** [comment]
Hola @juangon: 
Esto es simplemente para tener en cuenta el tema de los adjuntos en wiki y WCM en la gestión de cuotas

**Comment by juangon** [comment]
Creo que esta arreglado en https://github.com/LSUG-Projects/quota-control-portlet/commit/8069474e01df40c73b38bbc5aee7524cd92840a8
