### ISSUE TITLE
Add portlet titles for Server, Site and My Quota Portlet

### ISSUE THREAD

**Issue by luiscmas** [LSUG-Projects/quota-control-portlet#33]
Add portlet titles for Server, Site and My Quota Portlet

my-quota-portlet
server-quota-portlet
site-quota-portlet

**Comment by juangon** [comment]
Fixed in https://github.com/LSUG-Projects/quota-control-portlet/commit/8069474e01df40c73b38bbc5aee7524cd92840a8
